# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Going home
        run: |
          cd ~
        
      - name: Cloning into repo
        run: |
          git clone https://github.com/bhickta/YouTube-video-to-PDF-PPT-Images.git
          git clone https://github.com/bhickta/Duplicate-Image-Finder.git
          ls -a
          pwd

      - name: Installing requirements.txt
        run: |
          pip install -r /home/runner/work/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/requirements.txt
          pip install -r /home/runner/work/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/Duplicate-Image-Finder/requirements.txt

      - name: Where I i
        run: |
          ls
      
      # Running main.py
      - name: Running script
        run: |
          sh script.sh

      # Removing duplicates
      - name: Removing duplicates
        run: |
          echo 'y' | python /home/runner/work/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/Duplicate-Image-Finder/difPy/dif.py -A "/home/runner/work/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/Output/" -s "low" -d "true"

      - name: Push dir to Git
        # You may pin to the exact commit or the version.
        # uses: liziwl/git-push-action@abc14cffc5cecdb80f1bebe86becab5aca602a75
        uses: liziwl/git-push-action@v1.0.4
        with:
          # Username of token holder
          git_token_holder: bhickta
          # Token for the destination repo. Can be passed in using $\{{ secrets.GIT_TOKEN }}
          git_token: ${{ secrets.GithubToken }} # GithubToken: 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
          # Repository URL after "https://", like "github.com/USER_NAME/REPO_NAME.git"
          repository_url: github.com/bhickta/YouTube-video-to-PDF-PPT-Images.git
          # Directory to push
          push_dir: /home/runner/work/YouTube-video-to-PDF-PPT-Images/YouTube-video-to-PDF-PPT-Images/Output/
          # User to commit
          commit_user: bhickta
          # Email of the user to commit
          commit_email: nishantbhickta+code@gmail.com
          # Destination branch to push changes
          branch: gh-pages
          # Keep commit history
          keep_history: true
          # Commit messgae
          commit_message: Auto Commit
